language: go

notifications:
  email: false

env:
  global:
    - GOARCH=amd64

go: 
 - 1.8.x

install:
  - go get -v github.com/bmizerany/assert
  - go get -v github.com/mrb/hob
  
gobuild_args: -x -ldflags "-X main.VersionString v1.2.3" 
  
script:
 - go build -v -o bin/horeb

after_success:
  - tar -vzcf /tmp/horeb_linux_amd64.tar.gz bin/horeb
