language: go
go: 
 - 1.7.x

install:
  - go get github.com/bmizerany/assert
  - go get github.com/mrb/hob
  
gobuild_args: -x -ldflags "-X main.VersionString v1.2.3" 
  
script:
 - go build -v -o bin/horeb
